### ISSUE TITLE
No matching version found for vue-layui@^1.0.1

### ISSUE THREAD

**Issue by fank-cd** [kouchao/vue-layui#11]
你好，我安装的时候出现这个问题了，请问怎么解决呢
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'vue-layui',
1 verbose cli   '-S' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session 4392192eb2a48a80
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npm.taobao.org/vue-layui 254ms (from cache)
8 silly registry:manifest no matching version for vue-layui@^1.0.1 in the cache. Forcing revalidation.
9 http fetch GET 200 https://registry.npm.taobao.org/vue-layui 140ms
10 silly fetchPackageMetaData error for vue-layui@^1.0.1 No matching version found for vue-layui@^1.0.1
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 480ms
13 verbose type range
14 verbose stack vue-layui: No matching version found for vue-layui@^1.0.1
14 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-pick-manifest\index.js:101:11)
14 verbose stack     at fetchPackument.then.packument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:43:18)
14 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
14 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
14 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
14 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
14 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:694:18)
14 verbose stack     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
14 verbose stack     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
14 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
14 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
14 verbose stack     at runCallback (timers.js:705:18)
14 verbose stack     at tryOnImmediate (timers.js:676:5)
14 verbose stack     at processImmediate (timers.js:658:5)
15 verbose cwd D:\code\work_code\cykj_vue\cykj_vue
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "vue-layui" "-S"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ETARGET
21 error notarget No matching version found for vue-layui@^1.0.1
22 error notarget In most cases you or one of your dependencies are requesting
22 error notarget a package version that doesn't exist.
23 verbose exit [ 1, true ]

```

**Comment by kouchao** [comment]
这个版本是不能安装的   学习期间安装npm i vue-lay@0.1.2-alpha.9 -S    请不要用于生产环境

**Comment by fank-cd** [comment]
问题解决了，谢谢！




------------------ 原始邮件 ------------------
发件人: "kouchao"<notifications@github.com>; 
发送时间: 2019年9月16日(星期一) 下午3:05
收件人: "kouchao/vue-layui"<vue-layui@noreply.github.com>; 
抄送: "一的平方"<2464512446@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kouchao/vue-layui] No matching version found forvue-layui@^1.0.1 (#11)




这个版本是不能安装的   学习期间安装npm i vue-lay@0.1.2-alpha.9 -S    请不要用于生产环境
